/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CityPicker: typeof import('./src/components/CityPicker.vue')['default']
    Equipment: typeof import('./src/components/Tags/Equipment/index.vue')['default']
    EquipmentAddEdit: typeof import('./src/components/Tags/Equipment/EquipmentAddEdit.vue')['default']
    EzvizLive: typeof import('./src/components/Tags/Equipment/EzvizLive.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    IsLoading: typeof import('./src/components/IsLoading.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    PopUpPicker: typeof import('./src/components/PopUpPicker.vue')['default']
    PopUpSelector: typeof import('./src/components/PopUpSelector.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Title: typeof import('./src/components/Title.vue')['default']
    VanAddressEdit: typeof import('vant/es')['AddressEdit']
    VanBackTop: typeof import('vant/es')['BackTop']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCol: typeof import('vant/es')['Col']
    VanDatePicker: typeof import('vant/es')['DatePicker']
    VanDropdownItem: typeof import('vant/es')['DropdownItem']
    VanDropdownMenu: typeof import('vant/es')['DropdownMenu']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanNoticeBar: typeof import('vant/es')['NoticeBar']
    VanPicker: typeof import('vant/es')['Picker']
    VanPickerGroup: typeof import('vant/es')['PickerGroup']
    VanPopover: typeof import('vant/es')['Popover']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanRow: typeof import('vant/es')['Row']
    VanTimePicker: typeof import('vant/es')['TimePicker']
  }
}
